openapi: 3.0.1
info:
  contact:
    email: lampralexandros@gmail.com
  description: This is a sample openApi document
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://wabli.netlify.app/
  title: TempApi
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
- description: local host
  url: http://localhost:8080/v1
security:
- {}
tags:
- description: not yet ready
  name: test
paths:
  /test:
    post:
      operationId: createtest
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/test'
        description: data to be created
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/test'
          description: seccessful operation
      summary: Creates the data
      tags:
      - test
      x-eov-operation-handler: controllers/TestController
  /test/{testId}:
    delete:
      operationId: deletetest
      parameters:
      - description: the Id parameter
        explode: false
        in: path
        name: testId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: successful operation
      summary: Delete the element
      tags:
      - test
      x-eov-operation-handler: controllers/TestController
    get:
      operationId: gettest
      parameters:
      - description: the Id parameter
        explode: false
        in: path
        name: testId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/test'
          description: seccessful operation
      summary: Get the element
      tags:
      - test
      x-eov-operation-handler: controllers/TestController
    put:
      operationId: updatetest
      parameters:
      - description: the Id parameter
        explode: false
        in: path
        name: testId
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/test'
        description: data to be updated
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/test'
          description: seccessful operation
      summary: Updates the element
      tags:
      - test
      x-eov-operation-handler: controllers/TestController
  /test/getAll:
    get:
      operationId: getAlltest
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/test'
                type: array
          description: successful operation
      summary: Get all the data
      tags:
      - test
      x-method-getAll: "true"
      x-eov-operation-handler: controllers/TestController
components:
  schemas:
    test:
      example:
        test: test
        _id: _id
      properties:
        _id:
          type: string
        test:
          type: string
      required:
      - test
      type: object
